### ISSUE TITLE
Adicionar link para mais detalhes de termos interpolação e ternário (não tão comuns para iniciantes)

### ISSUE THREAD

**Issue by edmilton** [serradura/dicas-de-programacao-em-ruby#1]
Boas @serradura ! Complementando o assunto sobre link para mais detalhes, acho legal discutirmos por aqui se os links fazem sentido para depois mandar o PR. O que acha?

Dei prioridade para adicionarmos links em pt-BR e oficial. Sendo assim, minhas sugestões ficariam:

[Interpolação](https://guru-sp.github.io/tutorial_ruby/mais-sobre-strings.html)

[Ternário](https://guru-sp.github.io/tutorial_ruby/construcoes-simples.html)

O que acha? Faz sentido?
Gde. abraço!

**Comment by serradura** [comment]
Grande @edmilton. Muito obrigado pela colaboração! 👏 

Dá próxima vez sinta-se a vontade de abrir um Pull request. 😉 

Link para o commit: https://github.com/serradura/dicas-de-programacao-em-ruby/commit/79b163e7c91f3d4e7bf06bc9114a04652a02cf01
